package com.smartcampus.exception.mapper;

import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * GlobalExceptionMapper — Part 5: The "Leak-Proof" Safety Net
 *
 * Maps any uncaught Throwable → HTTP 500 Internal Server Error.
 * This ensures NO raw Java stack traces are ever returned to API consumers.
 *
 * CRITICAL DESIGN RULE:
 *   This mapper MUST NOT swallow WebApplicationExceptions (e.g., NotFoundException [404],
 *   MethodNotAllowedException [405], NotAcceptableException [406]).
 *   These are intentional HTTP status codes generated by JAX-RS itself and must be
 *   passed through or re-thrown so Jersey handles them correctly.
 *   Only genuinely unexpected exceptions (NullPointerException, ArrayIndexOutOfBoundsException, etc.)
 *   should be converted to HTTP 500.
 *
 * TO BE FULLY ANNOTATED AND EXPLAINED IN PART 5.
 */
@Provider
public class GlobalExceptionMapper implements ExceptionMapper<Throwable> {

    private static final Logger LOGGER = Logger.getLogger(GlobalExceptionMapper.class.getName());

    @Override
    public Response toResponse(Throwable ex) {
        // ── CRITICAL: Pass through JAX-RS WebApplicationExceptions ──────────
        // WebApplicationException and its subclasses (NotFoundException, etc.)
        // already encapsulate the correct HTTP status. Re-building them here
        // would incorrectly convert a 404 to a 500.
        if (ex instanceof WebApplicationException) {
            WebApplicationException wae = (WebApplicationException) ex;
            return wae.getResponse();
        }

        // ── Safety Net: Truly Unexpected Exceptions → HTTP 500 ──────────────
        // Log the full stack trace server-side (visible to developers in logs)
        // but return a sanitised, generic message to the client.
        LOGGER.log(Level.SEVERE, "Unexpected exception caught by global safety net mapper", ex);

        Map<String, Object> error = new LinkedHashMap<>();
        error.put("status", 500);
        error.put("error", "Internal Server Error");
        error.put("message", "An unexpected error occurred. Please contact the system administrator.");
        error.put("timestamp", System.currentTimeMillis());

        return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                .type(MediaType.APPLICATION_JSON)
                .entity(error)
                .build();
    }
}
